#!/usr/bin/env bash

update_upnp()
{
    APP_NAME=$1
    shift
    while (( "$#" )); do
        REDIRECTIONS="$REDIRECTIONS $1"
        shift
    done

    printf '%s\n' "Updating UPnP entry with redirections [$REDIRECTIONS]"

    GATEWAY=$(ip route | head -1 | awk '{print $3}')
    printf '%s\n' "Detected gateway is [$GATEWAY]"

    upnpc -e "$APP_NAME" -r $REDIRECTIONS

    printf '%s\n' "Done updating UPnP entry with port redirections [$REDIRECTIONS]"
}

MASTER_CONFIG_DIR="/etc/upnp-service"
MASTER_CONFIG="$MASTER_CONFIG_DIR/upnp.json"


#Parse config file

declare -A REDIRECTIONS
for APP_NAME in $(jq -r '.apps[]|.app_name' $MASTER_CONFIG)
do
    REDIRECTIONS[$APP_NAME]=$(jq -r '.apps[]|select(.app_name=='\"$APP_NAME\"').redirections[][]' $MASTER_CONFIG)
    update_upnp "$APP_NAME" ${REDIRECTIONS[$APP_NAME]}
done